### ISSUE TITLE
Feedbacks implementados

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#11]
- [x] O balão deve mudar o sprite se o feedback for bom ou ruim.
- [x] Feedbacks preenchidos

**Comment by IsadoraBeagle** [comment]
### **Arquivos**

- Combos que definem o comentário como positivo ou negativo: 
[ABP (Met1)](https://docs.google.com/spreadsheets/d/1XFLyc0MmTEA3UmFoY9VqE5mpZdscuRa68lsrbR75INk/edit#gid=1956759438&range=C15:C28)
[SAI (Met2)](https://docs.google.com/spreadsheets/d/1XFLyc0MmTEA3UmFoY9VqE5mpZdscuRa68lsrbR75INk/edit#gid=1170761617&range=C17:C22)
- [Comentário dos estudantes](https://docs.google.com/spreadsheets/d/1XFLyc0MmTEA3UmFoY9VqE5mpZdscuRa68lsrbR75INk/edit#gid=209768907&range=A1:C1)

- Elementos da interface
[Balão Positivo](https://drive.google.com/file/d/1dDz3SEYCNFs596D7sWH8y5Q0JR5nFAz1/view?usp=sharing)
[Balão Negativo](https://drive.google.com/file/d/1_2moC7Nx4ecHtsHVTwFBDYm-swM_ofDW/view?usp=sharing)


- [x] Pronto pra implementação
