### ISSUE TITLE
Implementação da cidade

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#111]
**Descrição e implementação**
Implementar a cidade.

- [x] Cenário
- [x] UI
- [x] Funcionamento

**Links para as referências e guias de interface**
[Link do fluxo](https://docs.google.com/presentation/d/1dWyDyD4Vc4ORjx5B0MsWqbSTdAQWH9QPYafZnGw2Cwo/edit#slide=id.g120b5af1374_0_928)

**Comment by vittamina** [comment]
hm interesting
