### ISSUE TITLE
Imprevistos implementados

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#12]
- [x] Pontuação.
- [x] Interface atualizada.
- [x] Imprevistos selecionados com base no nível de ensino.
- [x] Frase de feedback à resposta.
- [x] Imprevistos preenchidos.

**Comment by IsadoraBeagle** [comment]
### **Arquivos**

[Resposta dos estudantes a resolução do imprevisto](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=247067272&range=A1)

- [ ] Pronto pra implementação

[Elementos da Interface](https://drive.google.com/drive/folders/1ahHF7gil4vAw84x7_a0YEepoRVb4hqYK?usp=sharing)
- [ ] Pronto pra implementação
