### ISSUE TITLE
Implementar o novo feedback final na ABP

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#18]
- [x] Implementar os combos da ABP.
- [x] Implementar as telas.

**Comment by IsadoraBeagle** [comment]
### **Arquivos:**
[Texto dos Feedbacks da ABP (Met1) ](https://docs.google.com/spreadsheets/d/13OCXtYWyKsHQH205DqL0LQqB1UbXRsSobpLcXNVfYng/edit#gid=1611148719&range=A5)
- [X] Not ready yet
- [ ] Ta pronto, pode meter bala  

[Elementos da Interface](https://docs.google.com/spreadsheets/d/13OCXtYWyKsHQH205DqL0LQqB1UbXRsSobpLcXNVfYng/edit#gid=17225582&range=A7) 
- [X] Not ready yet
- [ ] Ta pronto, pode meter bala

**Comment by ErFer7** [comment]
https://github.com/game-comenius/Comenius3/issues/17#issuecomment-1067991789

**Comment by ErFer7** [comment]
A interface será implementada com base na tela de feedbacks finais da SAI por enquanto.
