### ISSUE TITLE
Implementar o tema da aula

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#21]
O tema da aula é atualizado no popup sua turma a cada fase.

**Comment by IsadoraBeagle** [comment]
### **Arquivos:**
[Texto da tela "Tema da Aula" na ABP (Met1)](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=101206611&range=C10:D11)

[Texto da tela "Tema da Aula" na SAI (Met2)](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=647568380&range=C10:D11)
- [X] Tão prontos, pode meter bala  

[Elementos da Interface](https://drive.google.com/drive/folders/1gjXUqTObMwGNOpGZrcDc67RdQlbNqYN3?usp=sharing) 
- [ ] Ta pronto, pode meter bala

**Comment by IsadoraBeagle** [comment]
Guia pro layout da tela "Tema da Aula - ABP (Met 1)"
<img width="863" alt="Screen Shot 2022-03-15 at 10 33 26" src="https://user-images.githubusercontent.com/94642351/158395475-381f28dc-ddad-497e-b09b-b161cb749348.png">

**Comment by IsadoraBeagle** [comment]
Guia pro layout do pop-up "Sua Turma" com tema da aula 
(a seta na lateral é para que o jogador possa visualizar o tema das outras fases, quando eles existirem) 
<img width="866" alt="Screen Shot 2022-03-15 at 11 07 15" src="https://user-images.githubusercontent.com/94642351/158395831-65f1c225-b5dc-4b0e-b2c8-cc0a8f18536e.png">
