### ISSUE TITLE
Implementar os popups de sequência didática

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#22]

**Comment by IsadoraBeagle** [comment]
- Estes pop-ups aparecem no momento que o jogador clica no botão "OK" após ter selecionado a segunda mídia para o Laboratório (ABP), Quarto e Sala de Aula (SAI). 
- O objetivo é fazer o jogador refletir se as mídias se encaixam com o momento da aula onde serão utilizadas

**Comment by IsadoraBeagle** [comment]
### **Arquivos:**
[Texto ABProb (Met 1) - Lab](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=101206611&range=C31:D31)
[Texto SAI (Met 2) - Quarto](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=647568380&range=C30:D30)
[Texto SAI (Met 2) - Sala](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit#gid=647568380&range=C44:D44)
- [X] Pronto pra implementação

[Elementos da Interface](https://docs.google.com/spreadsheets/d/13OCXtYWyKsHQH205DqL0LQqB1UbXRsSobpLcXNVfYng/edit#gid=17225582&range=A10)
- [ ] Pronto pra implementação

**Comment by IsadoraBeagle** [comment]
Guia pro layout da tela "Pop-up da sequência Didática - ABP (Met 1)"

<img width="873" alt="Screen Shot 2022-03-15 at 11 19 12" src="https://user-images.githubusercontent.com/94642351/158398333-5ca75d30-ba66-4536-aa87-fefcc8c33cc7.png">
