### ISSUE TITLE
Implementar o sistema linear na troca de cenas

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#23]

**Comment by IsadoraBeagle** [comment]
**Arquivos:**

[Guia de telas das fases 1 e 2 (v2.4.1)](https://docs.google.com/presentation/d/1HjVVa9LOZ57xnBXQt0h1PQMUPUn45AGReXdshUl881M/edit?usp=sharing )

[Guia de textos oficiais das fases 1 e 2 (v2.4.1)](https://docs.google.com/spreadsheets/d/16hlDZTT_aO1w6OtXKYUlexO_BFj24QpW9mn0hatYhbc/edit?usp=sharing)

[Exemplos de aplicação do texto e sprites](https://drive.google.com/drive/folders/1ZIFaIcn2u6QnhlTvtHG_m7AbGGw_p7bM?usp=sharing)

[Fluxograma da v2.4.1](https://drive.google.com/file/d/1dYLYU-SI-oQOVKqHcxjeGA-nm9e4sc-D/view?usp=sharing)
