### ISSUE TITLE
Atualizar a interface do menu.

### ISSUE THREAD

**Issue by ErFer7** [game-comenius/Comenius3#38]

**Comment by ErFer7** [comment]
O planejamento da maioria das telas precisa ser feito.

**Comment by IsadoraBeagle** [comment]
> O planejamento da maioria das telas precisa ser feito.

Essa seria a interface do Menu Principal? Quais atualizações seriam feitas?

**Comment by ErFer7** [comment]
O menu principal seria implementado com base nos slides, sendo assim é necessário que todos os recursos estejam disponíveis.

**Comment by IsadoraBeagle** [comment]
Todos os recursos pra 2.4 estão disponíveis :) 
[Links para acessar as guias e sprites que faltavam](https://docs.google.com/spreadsheets/d/13OCXtYWyKsHQH205DqL0LQqB1UbXRsSobpLcXNVfYng/edit#gid=913110972&range=A1)
