### ISSUE TITLE
Ajustes de usabilidade e jogabilidade

### ISSUE THREAD

**Issue by IsadoraBeagle** [game-comenius/Comenius3#47]
- [x] Na escolha de mídias, a opção Plataformas está com o ícone errado. [Este é o ícone correto](https://drive.google.com/file/d/1AzAvTb1B6DLuKIIejDzBcVAWPw1-N-WM/view?usp=sharing) 
- [x] Aumentar tamanho do texto nos comentários dos alunos sobre as mídias. 
- [x] Alterar o botão de avançar após comentário dos alunos por "Continuar" ao invés de "Ok".
- [x] Substituir sprite de bloco de notas (que aparece pequeno e abaixo do botão de ajuda no resumo do planejamento) por [este aqui](https://drive.google.com/file/d/1vBnoPz6BlDzWziKo71g8R4H8FUW0c8Pp/view?usp=sharing). 
- [x] Reduzir o tamanho dos hovers no menu.
- [x] Atualizar o subtítulo do espaço de aprendizagem no preview.
- [x] Durante o quiz a barra de pontuação deve ser sempre verde, independente da quantidade de pontos. Ela pode mudar no final, para ficar da mesma cor que a barra da tela de feedback. 
- [x] Adicionar hoover com texto nos botões "P" (texto:  `Pontuação`) e "A" (texto: `Duração da aula`) que aparecem no momento do quiz.
- [x] Adicionar marcador contendo porcentagem na ponta da barra de pontuação da tela de feedback.

**Comment by ErFer7** [comment]
A cena do menu deve estar livre para a edição primeiro.
