### ISSUE TITLE
Selecionar midias repetidas

### ISSUE THREAD

**Issue by IsadoraBeagle** [game-comenius/Comenius3#49]
**Descreva o bug**
O jogador pode selecionar duas mídias iguais para o mesmo espaço de ensino. 

**Como reproduzir o bug**
Para reproduzir o bug:
1. Vá para 'Planejamento da ABP'
2. Escolha 'Mídia 1'
3. Clique em 'OK'
4. Escolha 'Uma mídia igual a Midia 1'
5. Clique em 'Confirmar'
6. Veja o erro

**Comportamento experado**
A primeira mídia selecionada deveria aparecer como inativa na tela de escolha da segunda mídia. Isso evita que o comentário dos alunos apareça repetido no momento da aula. 

**Informações**
- Firefox 98.0.1
- Resolução de tela 1280 x 800

**Comment by ErFer7** [comment]
As cena do Menu deve estar livre para a edição primeiro
