### ISSUE TITLE
Ajustes de jogabilidade e usabilidade 2

### ISSUE THREAD

**Issue by IsadoraBeagle** [game-comenius/Comenius3#64]
- [x] Inserir nome da metodologia ao lado do ícone na tela de resumo das escolhas  **(ABP)**

- [x] Adicionar um 'x' no pop-up de resumo das escolhas da sala de aula **(ABP)**

- [x] Corrigir ícones referentes as mídias  no pop-up de resumo das escolhas da sala de aula **(ABP)**

- [x] Mudar a ordem do comentário dos estudantes para antes do quiz de acordo com [fluxo do jogo](https://drive.google.com/file/d/1pE3t1AHLz7kdLWpM3vFxDu9yohNxsxQd/view?usp=sharing) **(ABP e SAI)** 

- [x]   Corrigir cor da linha que une a combinação de mídias no feedback da Lurdinha 
(IDEAL = Verde, BOA = Azul e ARRISCADA = Vermelha)

- [x] Atualizar botões nos créditos para o novo formato

- [x] Corrigir bug do quarto do aluno com os [prints](https://drive.google.com/drive/folders/1TSdYwafjqpyUEfnTr4iTWQ85SB8CD_c-?usp=sharing) 

- [x] Substituir a opção de mídia "Livro Didático" por "Cadernos e Cartazes" na escolha de mídias do quarto **(SAI)**

- [x] Reduzir os hovers

- [x] Corrigir a falta de sprites no quiz ABP.
- [x] Alterar o tamanho do círculo de seleção do quiz ME.

- [x] Corrigir a cor dos sprites nos quizzes.
- [x] Ajustar a almofada do professor.

- [x] Adicionar os combos atualizados.

- [x] Mudar o tamanho do teclado no quarto.

- [x] Alterar a escala da interface no quarto.

- [x] Corrigir o bug em que alguns quizzes ficam sobrepostos à interface.
- [x] Aumentar os ícones do feedbacks.

- [x] Corrigir o bug em que o menu cascata não é acessível na página de agrupamentos.

- [x] Mudar a posição dos botões no popup de sequência didática.

**Comment by ErFer7** [comment]
- [ ] Substituir o ícone de expansão da explicação nas telas de mídias e outras.
